version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: portfolio-tools-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: portfolio_tools_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
